### ISSUE TITLE
how to contribute?

### ISSUE THREAD

**Issue by XertroV** [GreepTheSheep/nadeoservices-helper#2]
is there any info you can point to WRT how one can contribute?

I have a bunch of endpoints in angelscript here: https://github.com/XertroV/tm-cotd-hud/blob/master/src/CotdApi.as

I could probably contribute those to the demo plugin side without help, but WRT adding to the docs, idk where to start besides reading the code. 
If there's no existing docs you can point to (mb you're using a standard or something) then would it be possible to add a little 'developing' section to the readme or a contributing.md, etc?

**Comment by GreepTheSheep** [comment]
I'm actually making the contributing.md, should be out in the upcoming week.

Actually, just take a look about the .md meta (importantly) and their description.
The JSON file is auto-generated after a push on the main branch

**Comment by XertroV** [comment]
cool -- well seems easier than I guessed.

Notes for anyone else wondering:

* I checked https://github.com/GreepTheSheep/nadeoservices-helper/blob/main/.github/workflows/build-api.yml to figure out how to do the 'build' bit (it's just `npm i && npm run build`)
* There seems to be enough examples in the existing docs to answer most questions
* Seems like you can just add extra fields in `parameters.query[]` (e.g., I added `minimum` and `maximum` in #3 and the json out seems fine)

**Comment by GreepTheSheep** [comment]
Created [contributing.md file](https://github.com/GreepTheSheep/nadeoservices-helper/blob/main/CONTRIBUTING.md), closing this issue now
